/**
 * stitch-comparison-section.test.mjs
 * Phase 68 — Critique Stitch Comparison
 *
 * Tests: CRT-04 (Stitch Comparison section format, gating, exclusions)
 */
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { resolve } from 'path';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = resolve(__dirname, '..', '..');
const critiqueMd = readFileSync(resolve(ROOT, 'workflows', 'critique.md'), 'utf8');

describe('CRT-04: Stitch Comparison section', () => {
  test('## Stitch Comparison section present', () => {
    assert.ok(
      critiqueMd.includes('## Stitch Comparison'),
      'critique.md missing ## Stitch Comparison section'
    );
  });

  test('Stitch Comparison section is conditional on STITCH_ARTIFACTS', () => {
    const stitchSectionIdx = critiqueMd.indexOf('## Stitch Comparison');
    const stitchArtifactsBefore = critiqueMd.lastIndexOf('STITCH_ARTIFACTS', stitchSectionIdx);
    assert.ok(
      stitchArtifactsBefore !== -1,
      'critique.md Stitch Comparison section not gated on STITCH_ARTIFACTS'
    );
  });

  test('Stitch Comparison appears after Footer section', () => {
    const footerIdx = critiqueMd.indexOf('*Generated by PDE-OS /pde:critique');
    // Use lastIndexOf to find the actual output-template occurrence of ## Stitch Comparison
    // (not the prose references earlier in the document)
    const stitchIdx = critiqueMd.lastIndexOf('## Stitch Comparison');
    assert.ok(footerIdx !== -1, 'critique.md missing Footer section');
    assert.ok(stitchIdx !== -1, 'critique.md missing ## Stitch Comparison section');
    assert.ok(stitchIdx > footerIdx, '## Stitch Comparison must appear after Footer');
  });

  test('Token compliance percentage documented', () => {
    assert.ok(
      critiqueMd.includes('Token compliance') || critiqueMd.includes('token compliance'),
      'critique.md Stitch Comparison missing token compliance percentage'
    );
  });

  test('Properties Deviating subsection present', () => {
    assert.ok(
      critiqueMd.includes('Properties Deviating from Design System'),
      'critique.md Stitch Comparison missing Properties Deviating subsection'
    );
  });

  test('Novel Patterns subsection present', () => {
    assert.ok(
      critiqueMd.includes('Novel Patterns in Stitch Output'),
      'critique.md Stitch Comparison missing Novel Patterns subsection'
    );
  });

  test('Absent Patterns subsection present', () => {
    assert.ok(
      critiqueMd.includes('Patterns in Design System Absent from Stitch Output'),
      'critique.md Stitch Comparison missing Absent Patterns subsection'
    );
  });

  test('Stitch Comparison uses recommendations not findings', () => {
    assert.ok(
      critiqueMd.includes('recommendations') && critiqueMd.includes('Stitch Comparison'),
      'critique.md Stitch Comparison section does not distinguish recommendations from findings'
    );
  });

  test('Stitch Comparison not included in Action List', () => {
    assert.ok(
      critiqueMd.includes('Stitch Comparison recommendations are NOT included'),
      'critique.md Action List does not explicitly exclude Stitch Comparison recommendations'
    );
  });

  test('Stitch Comparison not added to DESIGN-STATE Open Critique Items', () => {
    assert.ok(
      critiqueMd.includes('Stitch Comparison recommendations are NOT added to DESIGN-STATE'),
      'critique.md does not explicitly exclude Stitch Comparison from DESIGN-STATE Open Critique Items'
    );
  });

  test('Composite score unaffected by Stitch Comparison', () => {
    // The blockquote in the Stitch Comparison output template must state scores reflect 4-perspective only.
    // Use lastIndexOf to find the actual output-template occurrence (not prose references).
    const stitchIdx = critiqueMd.lastIndexOf('## Stitch Comparison');
    const afterStitch = critiqueMd.slice(stitchIdx, stitchIdx + 500);
    assert.ok(
      afterStitch.includes('composite score') || afterStitch.includes('4-perspective'),
      'Stitch Comparison section does not clarify composite score is 4-perspective only'
    );
  });

  test('Empty STITCH_ARTIFACTS skips section entirely', () => {
    assert.ok(
      critiqueMd.includes('STITCH_ARTIFACTS is empty') && critiqueMd.includes('Skip this section entirely'),
      'critique.md does not skip Stitch Comparison when STITCH_ARTIFACTS is empty'
    );
  });
});
