// Auto-generated by /pde:wrap
// Binary: /opt/homebrew/bin/git
// Generated: 2026-03-29T02:04:39.865Z
// WARNING: Do not edit — regenerate with /pde:wrap

'use strict';

const path = require('path');
const { spawnSync } = require('child_process');

const SDK_BASE = "/Users/greyaltaer/code/projects/Platform Development Engine/packages/pde-mcp-server/node_modules/@modelcontextprotocol/sdk/dist/cjs";
const { McpServer } = require(path.join(SDK_BASE, 'server/mcp.js'));
const { StdioServerTransport } = require(path.join(SDK_BASE, 'server/stdio.js'));

const BINARY = "/opt/homebrew/bin/git";
const DRY_RUN = process.argv.includes('--dry-run');

const server = new McpServer({ name: "/opt/homebrew/bin/git", version: '1.0.0' });
server.registerTool(
  "git_clone",
  {
    description: "GIT-CLONE(1)                      Git Manual                      GIT-CLONE(1)\n\nN\bNA\bAM\bME\bE\n       git-clone - Clone a repository into a new directory\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       g\bgi\bit\bt c\bcl\blo\bon\bne\be [-\b--\b-t\bte\bem\bmp\bpl\bla\bat\bte\be=\b=_\b<_\bt_\be_\bm_\bp_\bl_\ba_\bt_\be_\b-_\bd_\bi_\br_\be_\bc_\bt_\bo_\br_\by_\b>]\n              [-\b-l\bl] [-\b-s\bs] [-\b--\b-n\bno\bo-\b-h\bha\bar\brd\bdl\bli\bin\bnk\bks\bs] [-\b-q\bq] [-\b-n\bn] [-\b--\b-b\bba\bar\bre\be] [-\b--\b-m\bmi\bir\brr\bro\bor\br]\n              [-\b-o\bo _\b<_\bn_\ba_\bm_\be_\b>] [-\b-b\bb _\b<_\bn_\ba_\bm_\be_\b>] [-\b-u\bu _\b<_\bu_\bp_\bl_\bo_\ba_\bd_\b-_\bp_\ba_\bc_\bk_\b>] [-\b--\b-r\bre\bef\bfe\ber\bre\ben\bnc\bce\be _\b<_\br_\be_\bp_\bo_\bs_\bi_\bt_\bo_\br_\by_\b>]\n              [-\b--\b-d\bdi\bis\bss\bso\boc\bci\bia\bat\bte\be] [-\b--\b-s\bse\bep\bpa\bar\bra\bat\bte\be-\b-g\bgi\bit\bt-\b-d\bdi\bir\br _\b<_\bg_\bi_\bt_\b-_\bd_\bi_\br_\b>]\n              [-\b--\b-d\bde\bep\bpt\bth\bh _\b<_\bd_\be_\bp_\bt_\bh_\b>] [-\b--\b-[n\bno\bo-\b-]s\bsi\bin\bng\bgl\ble\be-\b-b\bbr\bra\ban\bnc\bch\bh] [-\b--\b-n\bno\bo-\b-t\bta\bag\bgs\bs]\n              [-\b--\b-r\bre\bec\bcu\bur\brs\bse\be-\b-s\bsu\bub\bbm\bmo\bod\bdu\bul\ble\b",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["clone"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_init",
  {
    description: "GIT-INIT(1)                       Git Manual                       GIT-INIT(1)\n\nN\bNA\bAM\bME\bE\n       git-init - Create an empty Git repository or reinitialize an existing\n       one\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       g\bgi\bit\bt i\bin\bni\bit\bt [-\b-q\bq | -\b--\b-q\bqu\bui\bie\bet\bt] [-\b--\b-b\bba\bar\bre\be] [-\b--\b-t\bte\bem\bmp\bpl\bla\bat\bte\be=\b=_\b<_\bt_\be_\bm_\bp_\bl_\ba_\bt_\be_\b-_\bd_\bi_\br_\be_\bc_\bt_\bo_\br_\by_\b>]\n             [-\b--\b-s\bse\bep\bpa\bar\bra\bat\bte\be-\b-g\bgi\bit\bt-\b-d\bdi\bir\br _\b<_\bg_\bi_\bt_\b-_\bd_\bi_\br_\b>] [-\b--\b-o\bob\bbj\bje\bec\bct\bt-\b-f\bfo\bor\brm\bma\bat\bt=\b=_\b<_\bf_\bo_\br_\bm_\ba_\bt_\b>]\n             [-\b--\b-r\bre\bef\bf-\b-f\bfo\bor\brm\bma\bat\bt=\b=_\b<_\bf_\bo_\br_\bm_\ba_\bt_\b>]\n             [-\b-b\bb _\b<_\bb_\br_\ba_\bn_\bc_\bh_\b-_\bn_\ba_\bm_\be_\b> | -\b--\b-i\bin\bni\bit\bti\bia\bal\bl-\b-b\bbr\bra\ban\bnc\bch\bh=\b=_\b<_\bb_\br_\ba_\bn_\bc_\bh_\b-_\bn_\ba_\bm_\be_\b>]\n             [-\b--\b-s\bsh\bha\bar\bre\bed\bd[=\b=_\b<_\bp_\be_\br_\bm_\bi_\bs_\bs_\bi_\bo_\bn_\bs_\b>]] [_\b<_\bd_\bi_\br_\be_\bc_\bt_\bo_\br_\by_\b>]\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       This command creates an empty Git repository",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["init"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_add",
  {
    description: "GIT-ADD(1)                        Git Manual                        GIT-ADD(1)\n\nN\bNA\bAM\bME\bE\n       git-add - Add file contents to the index\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       g\bgi\bit\bt a\bad\bdd\bd [-\b--\b-v\bve\ber\brb\bbo\bos\bse\be | -\b-v\bv] [-\b--\b-d\bdr\bry\by-\b-r\bru\bun\bn | -\b-n\bn] [-\b--\b-f\bfo\bor\brc\bce\be | -\b-f\bf] [-\b--\b-i\bin\bnt\bte\ber\bra\bac\bct\bti\biv\bve\be | -\b-i\bi] [-\b--\b-p\bpa\bat\btc\bch\bh | -\b-p\bp]\n            [-\b--\b-e\bed\bdi\bit\bt | -\b-e\be] [-\b--\b-[n\bno\bo-\b-]a\bal\bll\bl | -\b-A\bA | -\b--\b-[n\bno\bo-\b-]i\big\bgn\bno\bor\bre\be-\b-r\bre\bem\bmo\bov\bva\bal\bl | [-\b--\b-u\bup\bpd\bda\bat\bte\be | -\b-u\bu]] [-\b--\b-s\bsp\bpa\bar\brs\bse\be]\n            [-\b--\b-i\bin\bnt\bte\ben\bnt\bt-\b-t\bto\bo-\b-a\bad\bdd\bd | -\b-N\bN] [-\b--\b-r\bre\bef\bfr\bre\bes\bsh\bh] [-\b--\b-i\big\bgn\bno\bor\bre\be-\b-e\ber\brr\bro\bor\brs\bs] [-\b--\b-i\big\bgn\bno\bor\bre\be-\b-m\bmi\bis\bss\bsi\bin\bng\bg] [-\b--\b-r\bre\ben\bno\bor\brm\bma\bal\bli\biz\bze\be]\n            [-\b--\b-c\bch\bhm\bmo\bod\bd=\b=(+\b+|-\b-)x\bx] [-\b--\b-p\bpa\bat\bth\bhs\bsp\bpe\bec\bc-\b-f\bfr\bro\bom\bm-\b-f\bfi\bil\ble\be=\b=_\b<_\bf_\bi_\bl_\be_\b> [-\b--\b-p\bpa\bat\bth\bhs\bsp\bpe\bec\b",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["add"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_mv",
  {
    description: "GIT-MV(1)                         Git Manual                         GIT-MV(1)\n\nN\bNA\bAM\bME\bE\n       git-mv - Move or rename a file, a directory, or a symlink\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\bm_\bv [<options>] <source>... <destination>\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       Move or rename a file, directory, or symlink.\n\n           git mv [-v] [-f] [-n] [-k] <source> <destination>\n           git mv [-v] [-f] [-n] [-k] <source> ... <destination-directory>\n\n       In the first form, it renames <source>, which must exist and be either\n       a file, symlink or directory, to <destination>. In the second form, the\n       last argument has to be an existing directory; the given sources will\n       be moved into this directory.\n\n       The index is updated after successful completion, but the change must\n       still be committed.\n\nO\bOP\bPT\bTI\bIO\bON\bNS\bS\n       -f, --force\n           Force renaming or moving of a file even if the <destination>\n           exists.\n\n       -k\n        ",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["mv"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_restore",
  {
    description: "GIT-RESTORE(1)                    Git Manual                    GIT-RESTORE(1)\n\nN\bNA\bAM\bME\bE\n       git-restore - Restore working tree files\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\br_\be_\bs_\bt_\bo_\br_\be [<options>] [--source=<tree>] [--staged] [--worktree] [--] <pathspec>...\n       _\bg_\bi_\bt _\br_\be_\bs_\bt_\bo_\br_\be [<options>] [--source=<tree>] [--staged] [--worktree] --pathspec-from-file=<file> [--pathspec-file-nul]\n       _\bg_\bi_\bt _\br_\be_\bs_\bt_\bo_\br_\be (-p|--patch) [<options>] [--source=<tree>] [--staged] [--worktree] [--] [<pathspec>...]\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       Restore specified paths in the working tree with some contents from a\n       restore source. If a path is tracked but does not exist in the restore\n       source, it will be removed to match the source.\n\n       The command can also be used to restore the content in the index with\n       -\b--\b-s\bst\bta\bag\bge\bed\bd, or restore both the working tree and the index with -\b--\b-s\bst\bta\bag\bge\bed\bd\n       -\b--\b-w\bwo\b",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["restore"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_rm",
  {
    description: "GIT-RM(1)                         Git Manual                         GIT-RM(1)\n\nN\bNA\bAM\bME\bE\n       git-rm - Remove files from the working tree and from the index\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\br_\bm [-f | --force] [-n] [-r] [--cached] [--ignore-unmatch]\n                 [--quiet] [--pathspec-from-file=<file> [--pathspec-file-nul]]\n                 [--] [<pathspec>...]\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       Remove files matching pathspec from the index, or from the working tree\n       and the index. g\bgi\bit\bt r\brm\bm will not remove a file from just your working\n       directory. (There is no option to remove a file only from the working\n       tree and yet keep it in the index; use /\b/b\bbi\bin\bn/\b/r\brm\bm if you want to do that.)\n       The files being removed have to be identical to the tip of the branch,\n       and no updates to their contents can be staged in the index, though\n       that default behavior can be overridden with the -\b-f\bf option. When\n       -\b--\b-c\bca",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["rm"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_bisect",
  {
    description: "GIT-BISECT(1)                     Git Manual                     GIT-BISECT(1)\n\nN\bNA\bAM\bME\bE\n       git-bisect - Use binary search to find the commit that introduced a bug\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\bb_\bi_\bs_\be_\bc_\bt <subcommand> <options>\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       The command takes various subcommands, and different options depending\n       on the subcommand:\n\n           git bisect start [--term-(bad|new)=<term-new> --term-(good|old)=<term-old>]\n                  [--no-checkout] [--first-parent] [<bad> [<good>...]] [--] [<pathspec>...]\n           git bisect (bad|new|<term-new>) [<rev>]\n           git bisect (good|old|<term-old>) [<rev>...]\n           git bisect terms [--term-(good|old) | --term-(bad|new)]\n           git bisect skip [(<rev>|<range>)...]\n           git bisect reset [<commit>]\n           git bisect (visualize|view)\n           git bisect replay <logfile>\n           git bisect log\n           git bisect run <cmd> [<arg>...]\n           git bi",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["bisect"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_diff",
  {
    description: "GIT-DIFF(1)                       Git Manual                       GIT-DIFF(1)\n\nN\bNA\bAM\bME\bE\n       git-diff - Show changes between commits, commit and working tree, etc\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       g\bgi\bit\bt d\bdi\bif\bff\bf [_\b<_\bo_\bp_\bt_\bi_\bo_\bn_\bs_\b>] [_\b<_\bc_\bo_\bm_\bm_\bi_\bt_\b>] [-\b--\b-] [_\b<_\bp_\ba_\bt_\bh_\b>...]\n       g\bgi\bit\bt d\bdi\bif\bff\bf [_\b<_\bo_\bp_\bt_\bi_\bo_\bn_\bs_\b>] -\b--\b-c\bca\bac\bch\bhe\bed\bd [-\b--\b-m\bme\ber\brg\bge\be-\b-b\bba\bas\bse\be] [_\b<_\bc_\bo_\bm_\bm_\bi_\bt_\b>] [-\b--\b-] [_\b<_\bp_\ba_\bt_\bh_\b>...]\n       g\bgi\bit\bt d\bdi\bif\bff\bf [_\b<_\bo_\bp_\bt_\bi_\bo_\bn_\bs_\b>] [-\b--\b-m\bme\ber\brg\bge\be-\b-b\bba\bas\bse\be] _\b<_\bc_\bo_\bm_\bm_\bi_\bt_\b> [_\b<_\bc_\bo_\bm_\bm_\bi_\bt_\b>...] _\b<_\bc_\bo_\bm_\bm_\bi_\bt_\b> [-\b--\b-] [_\b<_\bp_\ba_\bt_\bh_\b>...]\n       g\bgi\bit\bt d\bdi\bif\bff\bf [_\b<_\bo_\bp_\bt_\bi_\bo_\bn_\bs_\b>] _\b<_\bc_\bo_\bm_\bm_\bi_\bt_\b>`..._\b__\b__\b<_\bc_\bo_\bm_\bm_\bi_\bt_\b>_\b__\b_ [{empty}--{empty}]{empty} [_\b__\b__\b<_\bp_\ba_\bt_\bh_\b>_\b__\b_.\b..\b..]{empty}\n       {empty}`git d\bdi\bif\bff\bf [_\b<_\bo_\bp_\bt_\bi_\bo_\bn_\bs_\b>] _\b<_\bb_\bl_\bo_\bb_\b> _\b<_\bb_\bl",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["diff"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_grep",
  {
    description: "GIT-GREP(1)                       Git Manual                       GIT-GREP(1)\n\nN\bNA\bAM\bME\bE\n       git-grep - Print lines matching a pattern\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\bg_\br_\be_\bp [-a | --text] [-I] [--textconv] [-i | --ignore-case] [-w | --word-regexp]\n                  [-v | --invert-match] [-h|-H] [--full-name]\n                  [-E | --extended-regexp] [-G | --basic-regexp]\n                  [-P | --perl-regexp]\n                  [-F | --fixed-strings] [-n | --line-number] [--column]\n                  [-l | --files-with-matches] [-L | --files-without-match]\n                  [(-O | --open-files-in-pager) [<pager>]]\n                  [-z | --null]\n                  [ -o | --only-matching ] [-c | --count] [--all-match] [-q | --quiet]\n                  [--max-depth <depth>] [--[no-]recursive]\n                  [--color[=<when>] | --no-color]\n                  [--break] [--heading] [-p | --show-function]\n                  [-A <post-context>] [-B <pre-context>] [-C <co",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["grep"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_log",
  {
    description: "GIT-LOG(1)                        Git Manual                        GIT-LOG(1)\n\nN\bNA\bAM\bME\bE\n       git-log - Show commit logs\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\bl_\bo_\bg [<options>] [<revision-range>] [[--] <path>...]\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       Shows the commit logs.\n\n       List commits that are reachable by following the p\bpa\bar\bre\ben\bnt\bt links from the\n       given commit(s), but exclude commits that are reachable from the one(s)\n       given with a _\b^ in front of them. The output is given in reverse\n       chronological order by default.\n\n       You can think of this as a set operation. Commits reachable from any of\n       the commits given on the command line form a set, and then commits\n       reachable from any of the ones given with _\b^ in front are subtracted\n       from that set. The remaining commits are what comes out in the\n       command’s output. Various other options and paths parameters can be\n       used to further limit the result.\n\n       ",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["log"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_show",
  {
    description: "GIT-SHOW(1)                       Git Manual                       GIT-SHOW(1)\n\nN\bNA\bAM\bME\bE\n       git-show - Show various types of objects\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\bs_\bh_\bo_\bw [<options>] [<object>...]\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       Shows one or more objects (blobs, trees, tags and commits).\n\n       For commits it shows the log message and textual diff. It also presents\n       the merge commit in a special format as produced by _\bg_\bi_\bt _\bd_\bi_\bf_\bf_\b-_\bt_\br_\be_\be _\b-_\b-_\bc_\bc.\n\n       For tags, it shows the tag message and the referenced objects.\n\n       For trees, it shows the names (equivalent to _\bg_\bi_\bt _\bl_\bs_\b-_\bt_\br_\be_\be with\n       --name-only).\n\n       For plain blobs, it shows the plain contents.\n\n       Some options that _\bg_\bi_\bt _\bl_\bo_\bg command understands can be used to control\n       how the changes the commit introduces are shown.\n\n       This manual page describes only the most frequently used options.\n\nO\bOP\bPT\bTI\bIO\bON\bNS\bS\n      ",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["show"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_status",
  {
    description: "GIT-STATUS(1)                     Git Manual                     GIT-STATUS(1)\n\nN\bNA\bAM\bME\bE\n       git-status - Show the working tree status\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\bs_\bt_\ba_\bt_\bu_\bs [<options>] [--] [<pathspec>...]\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       Displays paths that have differences between the index file and the\n       current HEAD commit, paths that have differences between the working\n       tree and the index file, and paths in the working tree that are not\n       tracked by Git (and are not ignored by g\bgi\bit\bti\big\bgn\bno\bor\bre\be(5)). The first are\n       what you _\bw_\bo_\bu_\bl_\bd commit by running g\bgi\bit\bt c\bco\bom\bmm\bmi\bit\bt; the second and third are\n       what you _\bc_\bo_\bu_\bl_\bd commit by running _\bg_\bi_\bt _\ba_\bd_\bd before running g\bgi\bit\bt c\bco\bom\bmm\bmi\bit\bt.\n\nO\bOP\bPT\bTI\bIO\bON\bNS\bS\n       -s, --short\n           Give the output in the short-format.\n\n       -b, --branch\n           Show the branch and tracking info even in short-format.\n\n       --s",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["status"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_branch",
  {
    description: "GIT-BRANCH(1)                     Git Manual                     GIT-BRANCH(1)\n\nN\bNA\bAM\bME\bE\n       git-branch - List, create, or delete branches\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\bb_\br_\ba_\bn_\bc_\bh [--color[=<when>] | --no-color] [--show-current]\n               [-v [--abbrev=<n> | --no-abbrev]]\n               [--column[=<options>] | --no-column] [--sort=<key>]\n               [--merged [<commit>]] [--no-merged [<commit>]]\n               [--contains [<commit>]] [--no-contains [<commit>]]\n               [--points-at <object>] [--format=<format>]\n               [(-r | --remotes) | (-a | --all)]\n               [--list] [<pattern>...]\n       _\bg_\bi_\bt _\bb_\br_\ba_\bn_\bc_\bh [--track[=(direct|inherit)] | --no-track] [-f]\n               [--recurse-submodules] <branchname> [<start-point>]\n       _\bg_\bi_\bt _\bb_\br_\ba_\bn_\bc_\bh (--set-upstream-to=<upstream> | -u <upstream>) [<branchname>]\n       _\bg_\bi_\bt _\bb_\br_\ba_\bn_\bc_\bh --unset-upstream [<branchname>]\n       _\bg_\bi_\bt _\bb_\br_\ba_\bn_\bc_\bh (",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["branch"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_commit",
  {
    description: "GIT-COMMIT(1)                     Git Manual                     GIT-COMMIT(1)\n\nN\bNA\bAM\bME\bE\n       git-commit - Record changes to the repository\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\bc_\bo_\bm_\bm_\bi_\bt [-a | --interactive | --patch] [-s] [-v] [-u<mode>] [--amend]\n                  [--dry-run] [(-c | -C | --squash) <commit> | --fixup [(amend|reword):]<commit>]\n                  [-F <file> | -m <msg>] [--reset-author] [--allow-empty]\n                  [--allow-empty-message] [--no-verify] [-e] [--author=<author>]\n                  [--date=<date>] [--cleanup=<mode>] [--[no-]status]\n                  [-i | -o] [--pathspec-from-file=<file> [--pathspec-file-nul]]\n                  [(--trailer <token>[(=|:)<value>])...] [-S[<keyid>]]\n                  [--] [<pathspec>...]\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       Create a new commit containing the current contents of the index and\n       the given log message describing the changes. The new commit is a\n       direct child of HEAD, usual",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["commit"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_merge",
  {
    description: "GIT-MERGE(1)                      Git Manual                      GIT-MERGE(1)\n\nN\bNA\bAM\bME\bE\n       git-merge - Join two or more development histories together\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\bm_\be_\br_\bg_\be [-n] [--stat] [--no-commit] [--squash] [--[no-]edit]\n               [--no-verify] [-s <strategy>] [-X <strategy-option>] [-S[<keyid>]]\n               [--[no-]allow-unrelated-histories]\n               [--[no-]rerere-autoupdate] [-m <msg>] [-F <file>]\n               [--into-name <branch>] [<commit>...]\n       _\bg_\bi_\bt _\bm_\be_\br_\bg_\be (--continue | --abort | --quit)\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       Incorporates changes from the named commits (since the time their\n       histories diverged from the current branch) into the current branch.\n       This command is used by g\bgi\bit\bt p\bpu\bul\bll\bl to incorporate changes from another\n       repository and can be used by hand to merge changes from one branch\n       into another.\n\n       Assume the following history exists ",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["merge"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_rebase",
  {
    description: "GIT-REBASE(1)                     Git Manual                     GIT-REBASE(1)\n\nN\bNA\bAM\bME\bE\n       git-rebase - Reapply commits on top of another base tip\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\br_\be_\bb_\ba_\bs_\be [-i | --interactive] [<options>] [--exec <cmd>]\n               [--onto <newbase> | --keep-base] [<upstream> [<branch>]]\n       _\bg_\bi_\bt _\br_\be_\bb_\ba_\bs_\be [-i | --interactive] [<options>] [--exec <cmd>] [--onto <newbase>]\n               --root [<branch>]\n       _\bg_\bi_\bt _\br_\be_\bb_\ba_\bs_\be (--continue|--skip|--abort|--quit|--edit-todo|--show-current-patch)\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       If _\b<_\bb_\br_\ba_\bn_\bc_\bh_\b> is specified, g\bgi\bit\bt r\bre\beb\bba\bas\bse\be will perform an automatic g\bgi\bit\bt\n       s\bsw\bwi\bit\btc\bch\bh _\b<_\bb_\br_\ba_\bn_\bc_\bh_\b> before doing anything else. Otherwise it remains on the\n       current branch.\n\n       If _\b<_\bu_\bp_\bs_\bt_\br_\be_\ba_\bm_\b> is not specified, the upstream configured in\n       b\bbr\bra\ban\bnc\bch\bh.\b._\b<_\bn_\ba_\bm_\be_\b>.\b.r\bre\bem",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["rebase"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_reset",
  {
    description: "GIT-RESET(1)                      Git Manual                      GIT-RESET(1)\n\nN\bNA\bAM\bME\bE\n       git-reset - Reset current HEAD to the specified state\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\br_\be_\bs_\be_\bt [-q] [<tree-ish>] [--] <pathspec>...\n       _\bg_\bi_\bt _\br_\be_\bs_\be_\bt [-q] [--pathspec-from-file=<file> [--pathspec-file-nul]] [<tree-ish>]\n       _\bg_\bi_\bt _\br_\be_\bs_\be_\bt (--patch | -p) [<tree-ish>] [--] [<pathspec>...]\n       _\bg_\bi_\bt _\br_\be_\bs_\be_\bt [--soft | --mixed [-N] | --hard | --merge | --keep] [-q] [<commit>]\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       In the first three forms, copy entries from _\b<_\bt_\br_\be_\be_\b-_\bi_\bs_\bh_\b> to the index. In\n       the last form, set the current branch head (H\bHE\bEA\bAD\bD) to _\b<_\bc_\bo_\bm_\bm_\bi_\bt_\b>,\n       optionally modifying index and working tree to match. The\n       _\b<_\bt_\br_\be_\be_\b-_\bi_\bs_\bh_\b>/_\b<_\bc_\bo_\bm_\bm_\bi_\bt_\b> defaults to H\bHE\bEA\bAD\bD in all forms.\n\n       _\bg_\bi_\bt _\br_\be_\bs_\be_\bt [-q] [<tree-ish>] [--] <pathspec>..",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            },
            "mixed": {
                "type": "boolean",
                "description": "X       A     A"
            },
            "hard": {
                "type": "boolean",
                "description": "A       A     A"
            },
            "keep": {
                "type": "boolean",
                "description": "(disallowed)"
            },
            "merge": {
                "type": "boolean",
                "description": "A       A     A"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["reset"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_switch",
  {
    description: "GIT-SWITCH(1)                     Git Manual                     GIT-SWITCH(1)\n\nN\bNA\bAM\bME\bE\n       git-switch - Switch branches\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\bs_\bw_\bi_\bt_\bc_\bh [<options>] [--no-guess] <branch>\n       _\bg_\bi_\bt _\bs_\bw_\bi_\bt_\bc_\bh [<options>] --detach [<start-point>]\n       _\bg_\bi_\bt _\bs_\bw_\bi_\bt_\bc_\bh [<options>] (-c|-C) <new-branch> [<start-point>]\n       _\bg_\bi_\bt _\bs_\bw_\bi_\bt_\bc_\bh [<options>] --orphan <new-branch>\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       Switch to a specified branch. The working tree and the index are\n       updated to match the branch. All new commits will be added to the tip\n       of this branch.\n\n       Optionally a new branch could be created with either -\b-c\bc, -\b-C\bC,\n       automatically from a remote branch of same name (see -\b--\b-g\bgu\bue\bes\bss\bs), or\n       detach the working tree from any branch with -\b--\b-d\bde\bet\bta\bac\bch\bh, along with\n       switching.\n\n       Switching branches does not require a clean index and working",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["switch"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_tag",
  {
    description: "GIT-TAG(1)                        Git Manual                        GIT-TAG(1)\n\nN\bNA\bAM\bME\bE\n       git-tag - Create, list, delete or verify a tag object signed with GPG\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\bt_\ba_\bg [-a | -s | -u <key-id>] [-f] [-m <msg> | -F <file>] [-e]\n               [(--trailer <token>[(=|:)<value>])...]\n               <tagname> [<commit> | <object>]\n       _\bg_\bi_\bt _\bt_\ba_\bg -d <tagname>...\n       _\bg_\bi_\bt _\bt_\ba_\bg [-n[<num>]] -l [--contains <commit>] [--no-contains <commit>]\n               [--points-at <object>] [--column[=<options>] | --no-column]\n               [--create-reflog] [--sort=<key>] [--format=<format>]\n               [--merged <commit>] [--no-merged <commit>] [<pattern>...]\n       _\bg_\bi_\bt _\bt_\ba_\bg -v [--format=<format>] <tagname>...\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       Add a tag reference in r\bre\bef\bfs\bs/\b/t\bta\bag\bgs\bs/\b/, unless -\b-d\bd/\b/-\b-l\bl/\b/-\b-v\bv is given to delete,\n       list or verify tags.\n\n       Unless -\b-f\bf is given,",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["tag"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_fetch",
  {
    description: "GIT-FETCH(1)                      Git Manual                      GIT-FETCH(1)\n\nN\bNA\bAM\bME\bE\n       git-fetch - Download objects and refs from another repository\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\bf_\be_\bt_\bc_\bh [<options>] [<repository> [<refspec>...]]\n       _\bg_\bi_\bt _\bf_\be_\bt_\bc_\bh [<options>] <group>\n       _\bg_\bi_\bt _\bf_\be_\bt_\bc_\bh --multiple [<options>] [(<repository> | <group>)...]\n       _\bg_\bi_\bt _\bf_\be_\bt_\bc_\bh --all [<options>]\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       Fetch branches and/or tags (collectively, \"refs\") from one or more\n       other repositories, along with the objects necessary to complete their\n       histories. Remote-tracking branches are updated (see the description of\n       <refspec> below for ways to control this behavior).\n\n       By default, any tag that points into the histories being fetched is\n       also fetched; the effect is to fetch tags that point at branches that\n       you are interested in. This default behavior can be changed by",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["fetch"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_pull",
  {
    description: "GIT-PULL(1)                       Git Manual                       GIT-PULL(1)\n\nN\bNA\bAM\bME\bE\n       git-pull - Fetch from and integrate with another repository or a local\n       branch\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\bp_\bu_\bl_\bl [<options>] [<repository> [<refspec>...]]\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       Incorporates changes from a remote repository into the current branch.\n       If the current branch is behind the remote, then by default it will\n       fast-forward the current branch to match the remote. If the current\n       branch and the remote have diverged, the user needs to specify how to\n       reconcile the divergent branches with -\b--\b-r\bre\beb\bba\bas\bse\be or -\b--\b-n\bno\bo-\b-r\bre\beb\bba\bas\bse\be (or the\n       corresponding configuration option in p\bpu\bul\bll\bl.\b.r\bre\beb\bba\bas\bse\be).\n\n       More precisely, g\bgi\bit\bt p\bpu\bul\bll\bl runs g\bgi\bit\bt f\bfe\bet\btc\bch\bh with the given parameters and\n       then depending on configuration options or command line flags, wil",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["pull"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);

server.registerTool(
  "git_push",
  {
    description: "GIT-PUSH(1)                       Git Manual                       GIT-PUSH(1)\n\nN\bNA\bAM\bME\bE\n       git-push - Update remote refs along with associated objects\n\nS\bSY\bYN\bNO\bOP\bPS\bSI\bIS\bS\n       _\bg_\bi_\bt _\bp_\bu_\bs_\bh [--all | --branches | --mirror | --tags] [--follow-tags] [--atomic] [-n | --dry-run] [--receive-pack=<git-receive-pack>]\n                  [--repo=<repository>] [-f | --force] [-d | --delete] [--prune] [-q | --quiet] [-v | --verbose]\n                  [-u | --set-upstream] [-o <string> | --push-option=<string>]\n                  [--[no-]signed|--signed=(true|false|if-asked)]\n                  [--force-with-lease[=<refname>[:<expect>]] [--force-if-includes]]\n                  [--no-verify] [<repository> [<refspec>...]]\n\nD\bDE\bES\bSC\bCR\bRI\bIP\bPT\bTI\bIO\bON\bN\n       Updates remote refs using local refs, while sending objects necessary\n       to complete the given refs.\n\n       You can make interesting things happen to a repository every time you\n       push into it, by setting up ",
    inputSchema: {
        "type": "object",
        "properties": {
            "useJson": {
                "type": "boolean",
                "description": "Append --json flag to command"
            }
        }
    },
    annotations: { readOnlyHint: false },
  },
  async (input) => {
    const args = [...["push"]];
    if (input && input.useJson) args.push('--json');
    if (input) {
      for (const [key, val] of Object.entries(input)) {
        if (key === 'useJson') continue;
        if (val !== undefined && val !== null && val !== false) {
          args.push('--' + key);
          if (val !== true) args.push(String(val));
        }
      }
    }
    if (DRY_RUN) {
      return { content: [{ type: 'text', text: JSON.stringify({ dryRun: true, command: [BINARY, ...args] }) }] };
    }
    const r = spawnSync(BINARY, args, { encoding: 'utf8', timeout: 30000 });
    let data;
    try { data = JSON.parse(r.stdout); } catch (_) { data = { stdout: (r.stdout || '').trim(), stderr: (r.stderr || '').trim(), exitCode: r.status !== null ? r.status : -1 }; }
    return { content: [{ type: 'text', text: JSON.stringify(data) }] };
  }
);
async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
}

main().catch(err => {
  process.stderr.write(err.message + '\n');
  process.exit(1);
});
