// Auto-generated by /pde:ingest
// Source: tests/phase-163/fixtures/openapi-petstore.json
// Generated: 2026-03-29T06:15:08.419Z
// WARNING: stub execute functions — customize before production use

import { tool } from 'ai';
import { z } from 'zod';
export const listPets = tool({
  description: "List all pets",
  inputSchema: z.object({
    limit: z.number().optional()
  }),
  execute: async (input) => {
    // TODO: set base URL
    const res = await fetch(`${process.env.API_BASE_URL || ''}/pets`, { method: 'GET' });
    return res.json();
  },
});

export const createPet = tool({
  description: "Create a pet",
  inputSchema: z.object({
    id: z.number().optional(),
    name: z.string(),
    tag: z.string().optional()
  }),
  execute: async (input) => {
    // TODO: set base URL
    const res = await fetch(`${process.env.API_BASE_URL || ''}/pets`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(input) });
    return res.json();
  },
});

export const getPet = tool({
  description: "Get a pet by ID",
  inputSchema: z.object({
    petId: z.string()
  }),
  execute: async (input) => {
    // TODO: set base URL
    const res = await fetch(`${process.env.API_BASE_URL || ''}/pets/{petId}`, { method: 'GET' });
    return res.json();
  },
});
